# Import packages

In [1]:
!pip install import_ipynb
!pip install lazypredict
!pip install underthesea
!pip install demoji
!pip install pyvi

  Using cached scikit_learn-0.23.1-cp37-cp37m-manylinux1_x86_64.whl (6.8 MB)
  Using cached scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scipy-1.7.3:
      Successfully uninstalled scipy-1.7.3
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.2
    Uninstalling scikit-learn-0.24.2:
      Successfully uninstalled scikit-learn-0.24.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.23.1 which is incompatible.
smac 1.2 requires scipy>=1.7.0, but you have scipy 1.5.4 which is incompatible.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.23.1 which is incompatible.
gym 0.17.3 requires cloudpickle<1.7.0,>=1.2.0, but you have c

In [30]:
# !apt-get install build-essential swig
# !pip install auto-sklearn
# !pip install tpot

In [2]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [3]:
%cd '/content/gdrive/MyDrive/LDS0_K273_DamThiMinhPhuong/Project/Project3_SentimentAnalysis'

/content/gdrive/MyDrive/LDS0_K273_DamThiMinhPhuong/Project/Project3_SentimentAnalysis


In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

import import_ipynb
import Lib3

importing Jupyter notebook from Lib3.ipynb


In [5]:
from underthesea import word_tokenize, pos_tag, sent_tokenize
import regex
import demoji
from pyvi import ViPosTagger, ViTokenizer
import string
from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [7]:
# from autosklearn.classification import AutoSklearnClassifier
# import sklearn.metrics

# Load and Prepare data

In [6]:
df = pd.read_csv('data/foodyDataFinal_clean.csv', index_col=0)

In [7]:
df.shape

(70639, 6)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70639 entries, 0 to 77661
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   name               70639 non-null  object 
 1   review_text        70639 non-null  object 
 2   review_score       70639 non-null  float64
 3   review_score_bins  70639 non-null  object 
 4   label              70639 non-null  int64  
 5   review_text_clean  70639 non-null  object 
dtypes: float64(1), int64(1), object(4)
memory usage: 3.8+ MB


In [9]:
df['label2'] = [0 if x<7.5 else 1 for x in df.review_score]

In [10]:
text_data = np.array(df['review_text_clean'])
text_data

array(['gà mắm phô kéo sợi siêu ngon giá mềm .',
       'gà hàn phô kéo sợi siêu ngon giá mềm .',
       'gà rán phô kéo sợi sốt ngon .', ...,
       'dân thích giới_thiệu ngon vô liền . hình_như xưa tiếng . thích phở_tái cảm_nhận độ thơm bò . ngon . bánh_phở bình_thường không_đặc_biệt đường bít dời đâu . khẩu_vị mặn . bò mềm ngon . bò mà_còn bánh_phở . tương chấm không_đặc_biệt lắm . ngon không_tương chấm quyết_định chất_lượng . hình phở_tái mì gói tái vị . .',
       'tài_hưng ời mở_cửa nhào dô bún_bò giò hụt_hẫng . bún_bò màu đậm . bún_bò bò bò ngon mềm khỏi mỡ không_ngấy . miếng không_tô hình chà bá nện giá_cả chời rẻ . ngặt chạy phút .',
       'đợt lạ không_tạo địa_điểm bình_luận tiềm tự_dưng lắm ngon bá cháy . bò mềm lắm nước_lèo ngon trí đẹp . bàn tỏi sống ngâm_giấm giá trụng sẵn không_cần kêu trà đá . tầm nghỉ chiều_tối tiếp . tút .'],
      dtype=object)

In [14]:
count = CountVectorizer(max_features=10000)
count.fit(text_data)
bag_of_words = count.transform(text_data)
bag_of_words

<70639x10000 sparse matrix of type '<class 'numpy.int64'>'
	with 1548419 stored elements in Compressed Sparse Row format>

In [15]:
X = bag_of_words.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
X.shape

(70639, 10000)

In [24]:
y = np.array(df['label'])

In [25]:
y.shape

(70639,)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [27]:
X_train[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
y_train[:5]

array([1, 1, 1, 0, 1])

# LazyPredict 1

In [ ]:
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

100%|██████████| 29/29 [48:21<00:00, 100.04s/it]


In [ ]:
models

Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model                                                                           
BernoulliNB                        0.87               0.84     0.84      0.88   
NearestCentroid                    0.90               0.84     0.84      0.90   
SGDClassifier                      0.91               0.77     0.77      0.91   
LGBMClassifier                     0.92               0.76     0.76      0.91   
LogisticRegression                 0.91               0.76     0.76      0.91   
ExtraTreesClassifier               0.92               0.76     0.76      0.91   
RandomForestClassifier             0.91               0.75     0.75      0.91   
GaussianNB                         0.68               0.75     0.75      0.73   
XGBClassifier                      0.92               0.75     0.75      0.91   
BaggingClassifier                  0.89               0.75     0.75      0.89   
LinearSVC                          0.91               0.75     0.75      0.90   
Perceptron                         0.89               0.74     0.74      0.89   
DecisionTreeClassifier             0.87               0.73     0.73      0.87   
PassiveAggressiveClassifier        0.87               0.72     0.72      0.87   
LinearDiscriminantAnalysis         0.90               0.71     0.71      0.89   
ExtraTreeClassifier                0.86               0.71     0.71      0.86   
CalibratedClassifierCV             0.91               0.71     0.71      0.89   
SVC                                0.91               0.70     0.70      0.89   
AdaBoostClassifier                 0.90               0.70     0.70      0.89   
RidgeClassifier                    0.90               0.66     0.66      0.88   
RidgeClassifierCV                  0.90               0.66     0.66      0.88   
KNeighborsClassifier               0.86               0.63     0.63      0.85   
QuadraticDiscriminantAnalysis      0.83               0.57     0.57      0.82   
LabelPropagation                   0.20               0.51     0.51      0.16   
LabelSpreading                     0.20               0.51     0.51      0.16   
DummyClassifier                    0.77               0.50     0.50      0.77   

                               Time Taken  
Model                                      
BernoulliNB                          1.73  
NearestCentroid                      1.74  
SGDClassifier                       11.54  
LGBMClassifier                      11.31  
LogisticRegression                   4.02  
ExtraTreesClassifier                65.51  
RandomForestClassifier              33.38  
GaussianNB                           1.80  
XGBClassifier                       48.56  
BaggingClassifier                   96.73  
LinearSVC                           72.05  
Perceptron                           2.20  
DecisionTreeClassifier              20.77  
PassiveAggressiveClassifier          2.38  
LinearDiscriminantAnalysis           9.50  
ExtraTreeClassifier                  1.97  
CalibratedClassifierCV             275.24  
SVC                               1333.99  
AdaBoostClassifier                  29.62  
RidgeClassifier                      2.53  
RidgeClassifierCV                    7.61  
KNeighborsClassifier               722.10  
QuadraticDiscriminantAnalysis        8.55  
LabelPropagation                    58.48  
LabelSpreading                      72.88  
DummyClassifier                      1.31

Nhận xét:
- Với target chỉ có 2 class, các model cho kết qủa khá tốt
- => Ta sẽ lựa chọn phương án này và thực hiện một số phương pháp khác để tối ưu 

# LazyPredict 2

In [17]:
y = np.array(df['label2'])

In [18]:
y.shape

(70639,)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [21]:
X_train[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
y_train[:5]

array([1, 1, 1, 0, 1])

In [23]:
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

  0%|          | 0/29 [04:44<?, ?it/s]


KeyboardInterrupt: ignored

In [ ]:
models

# Automated Machine Learning (AutoML)

In [ ]:
clf_auto = AutoSklearnClassifier(time_left_for_this_task=3600, per_run_time_limit=None, n_jobs=-1)
clf_auto.fit(X_train, y_train)

AutoSklearnClassifier(n_jobs=-1, per_run_time_limit=1440)

In [ ]:
y_hat = clf_auto.predict(X_test)

In [ ]:
sklearn.metrics.accuracy_score(y_test, y_hat)

0.9174412848578186

In [ ]:
clf_auto.show_models

<bound method AutoSklearnEstimator.show_models of AutoSklearnClassifier(n_jobs=-1, per_run_time_limit=1440)>

In [ ]:
# clf_auto.cv_results_

In [ ]:
# summarize
print(clf_auto.sprint_statistics())

auto-sklearn results:
  Dataset name: aec1650a-a5c3-11ec-8930-0242ac1c0002
  Metric: accuracy
  Best validation score: 0.911964
  Number of target algorithm runs: 76
  Number of successful target algorithm runs: 63
  Number of crashed target algorithm runs: 6
  Number of target algorithms that exceeded the time limit: 7
  Number of target algorithms that exceeded the memory limit: 0



In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print('--- Confusion matrix\n', confusion_matrix(y_test, y_hat))
print('--- Classification report\n',classification_report(y_test, y_hat))

--- Confusion matrix
 [[ 1484  1009]
 [  492 15196]]
--- Classification report
               precision    recall  f1-score   support

           0       0.75      0.60      0.66      2493
           1       0.94      0.97      0.95     15688

    accuracy                           0.92     18181
   macro avg       0.84      0.78      0.81     18181
weighted avg       0.91      0.92      0.91     18181



In [ ]:
# TPOT (Tree-based)
from sklearn.model_selection import RepeatedStratifiedKFold
from tpot import TPOTClassifier

In [ ]:
cv = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=0)
model = TPOTClassifier(generations=4, population_size=50,cv=cv, scoring='accuracy', verbosity=2, 
                       random_state=0, n_jobs=-1)
model.fit(X_train, y_train)

[WARNING] [2022-03-17 08:31:07,705:stopit] Code block execution exceeded 10 seconds timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tpot/decorators.py", line 57, in time_limited_call
    func(*args)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 341, in fit
    Xt = self._fit(X, y, **fit_params_steps)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 307, in _fit
    **fit_params_steps[name])
  File "/usr/local/lib/python3.7/dist-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/base.py", line 702, in fit_transform
    return self

In [ ]:
!pip install hpsklearn

     |████████████████████████████████| 154 kB 6.0 MB/s 
  Created wheel for hpsklearn: filename=hpsklearn-0.1.0-py3-none-any.whl size=23913 sha256=93baa07c7950ea83d9e97d8a8d39066330ab4444fe8ba3d1e3c6bcf9fe759007
  Stored in directory: /root/.cache/pip/wheels/b2/22/23/9207fbe861f70774b563f909a415b228450bfcf863c64ac1e8
Successfully built hpsklearn


In [ ]:
from hpsklearn import HyperoptEstimator, any_classifier, any_preprocessing
from hyperopt import tpe

In [ ]:
model2 = HyperoptEstimator()
model2.fit(X_train, y_train)
acc = model.score(X_test, y_test)
acc

  0%|          | 0/1 [1:45:15<?, ?it/s, best loss: ?]


KeyboardInterrupt: ignored

In [ ]:
print(model.best_model())